def create_repository_publicized():
    return ["repository",
            {
                "action": "privatized",
                "repository": {
                    "id": 27496774,
                    "name": "conciliacao",
                    "full_name": "baxterandthehackers/new-repository",
                    "owner": {
                        "login": "baxterandthehackers",
                        "id": 7649605,
                        "avatar_url": "https://avatars.githubusercontent.com/u/7649605?v=3",
                        "gravatar_id": "",
                        "url": "https://api.github.com/users/baxterandthehackers",
                        "html_url": "https://github.com/baxterandthehackers",
                        "followers_url": "https://api.github.com/users/baxterandthehackers/followers",
                        "following_url": "https://api.github.com/users/baxterandthehackers/following{/other_user}",
                        "gists_url": "https://api.github.com/users/baxterandthehackers/gists{/gist_id}",
                        "starred_url": "https://api.github.com/users/baxterandthehackers/starred{/owner}{/repo}",
                        "subscriptions_url": "https://api.github.com/users/baxterandthehackers/subscriptions",
                        "organizations_url": "https://api.github.com/users/baxterandthehackers/orgs",
                        "repos_url": "https://api.github.com/users/baxterandthehackers/repos",
                        "events_url": "https://api.github.com/users/baxterandthehackers/events{/privacy}",
                        "received_events_url": "https://api.github.com/users/baxterandthehackers/received_events",
                        "type": "Organization",
                        "site_admin": False
                    },
                    "private": False,
                    "html_url": "https://github.com/baxterandthehackers/new-repository",
                    "description": "",
                    "fork": False,
                    "url": "https://api.github.com/repos/baxterandthehackers/new-repository",
                    "forks_url": "https://api.github.com/repos/baxterandthehackers/new-repository/forks",
                    "keys_url": "https://api.github.com/repos/baxterandthehackers/new-repository/keys{/key_id}",
                    "collaborators_url": "https://api.github.com/repos/baxterandthehackers/new-repository/collaborators{/collaborator}",
                    "teams_url": "https://api.github.com/repos/baxterandthehackers/new-repository/teams",
                    "hooks_url": "https://api.github.com/repos/baxterandthehackers/new-repository/hooks",
                    "issue_events_url": "https://api.github.com/repos/baxterandthehackers/new-repository/issues/events{/number}",
                    "events_url": "https://api.github.com/repos/baxterandthehackers/new-repository/events",
                    "assignees_url": "https://api.github.com/repos/baxterandthehackers/new-repository/assignees{/user}",
                    "branches_url": "https://api.github.com/repos/baxterandthehackers/new-repository/branches{/branch}",
                    "tags_url": "https://api.github.com/repos/baxterandthehackers/new-repository/tags",
                    "blobs_url": "https://api.github.com/repos/baxterandthehackers/new-repository/git/blobs{/sha}",
                    "git_tags_url": "https://api.github.com/repos/baxterandthehackers/new-repository/git/tags{/sha}",
                    "git_refs_url": "https://api.github.com/repos/baxterandthehackers/new-repository/git/refs{/sha}",
                    "trees_url": "https://api.github.com/repos/baxterandthehackers/new-repository/git/trees{/sha}",
                    "statuses_url": "https://api.github.com/repos/baxterandthehackers/new-repository/statuses/{sha}",
                    "languages_url": "https://api.github.com/repos/baxterandthehackers/new-repository/languages",
                    "stargazers_url": "https://api.github.com/repos/baxterandthehackers/new-repository/stargazers",
                    "contributors_url": "https://api.github.com/repos/baxterandthehackers/new-repository/contributors",
                    "subscribers_url": "https://api.github.com/repos/baxterandthehackers/new-repository/subscribers",
                    "subscription_url": "https://api.github.com/repos/baxterandthehackers/new-repository/subscription",
                    "commits_url": "https://api.github.com/repos/baxterandthehackers/new-repository/commits{/sha}",
                    "git_commits_url": "https://api.github.com/repos/baxterandthehackers/new-repository/git/commits{/sha}",
                    "comments_url": "https://api.github.com/repos/baxterandthehackers/new-repository/comments{/number}",
                    "issue_comment_url": "https://api.github.com/repos/baxterandthehackers/new-repository/issues/comments/{number}",
                    "contents_url": "https://api.github.com/repos/baxterandthehackers/new-repository/contents/{+path}",
                    "compare_url": "https://api.github.com/repos/baxterandthehackers/new-repository/compare/{base}...{head}",
                    "merges_url": "https://api.github.com/repos/baxterandthehackers/new-repository/merges",
                    "archive_url": "https://api.github.com/repos/baxterandthehackers/new-repository/{archive_format}{/ref}",
                    "downloads_url": "https://api.github.com/repos/baxterandthehackers/new-repository/downloads",
                    "issues_url": "https://api.github.com/repos/baxterandthehackers/new-repository/issues{/number}",
                    "pulls_url": "https://api.github.com/repos/baxterandthehackers/new-repository/pulls{/number}",
                    "milestones_url": "https://api.github.com/repos/baxterandthehackers/new-repository/milestones{/number}",
                    "notifications_url": "https://api.github.com/repos/baxterandthehackers/new-repository/notifications{?since,all,participating}",
                    "labels_url": "https://api.github.com/repos/baxterandthehackers/new-repository/labels{/name}",
                    "releases_url": "https://api.github.com/repos/baxterandthehackers/new-repository/releases{/id}",
                    "created_at": "2014-12-03T16:39:25Z",
                    "updated_at": "2014-12-03T16:39:25Z",
                    "pushed_at": "2014-11-03T17:39:25Z",
                    "git_url": "git://github.com/baxterandthehackers/new-repository.git",
                    "ssh_url": "git@github.com:baxterandthehackers/new-repository.git",
                    "clone_url": "https://github.com/baxterandthehackers/new-repository.git",
                    "svn_url": "https://github.com/baxterandthehackers/new-repository",
                    "homepage": None,
                    "size": 0,
                    "stargazers_count": 0,
                    "watchers_count": 0,
                    "language": None,
                    "has_issues": True,
                    "has_downloads": True,
                    "has_wiki": True,
                    "has_pages": False,
                    "forks_count": 0,
                    "mirror_url": None,
                    "open_issues_count": 0,
                    "forks": 0,
                    "open_issues": 0,
                    "watchers": 0,
                    "default_branch": "master"
                },
                "organization": {
                    "login": "stone-payments",
                    "id": 7649605,
                    "url": "https://api.github.com/orgs/baxterandthehackers",
                    "repos_url": "https://api.github.com/orgs/baxterandthehackers/repos",
                    "events_url": "https://api.github.com/orgs/baxterandthehackers/events",
                    "members_url": "https://api.github.com/orgs/baxterandthehackers/members{/member}",
                    "public_members_url": "https://api.github.com/orgs/baxterandthehackers/public_members{/member}",
                    "avatar_url": "https://avatars.githubusercontent.com/u/7649605?v=2"
                },
                "sender": {
                    "login": "baxterthehacker",
                    "id": 6752317,
                    "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=2",
                    "gravatar_id": "",
                    "url": "https://api.github.com/users/baxterthehacker",
                    "html_url": "https://github.com/baxterthehacker",
                    "followers_url": "https://api.github.com/users/baxterthehacker/followers",
                    "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
                    "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
                    "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
                    "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
                    "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
                    "repos_url": "https://api.github.com/users/baxterthehacker/repos",
                    "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
                    "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
                    "type": "User",
                    "site_admin": False
                }
            }
            ]


def new_commit():
    return ["push",
            {'after': 'cbc97cbe5adb32d73a5696870e5a8c8515e3badd',
             'base_ref': None,
             'before': '2bbf15e032fa7958947427cc34587fac7d2ba1f5',
             'commits': [{'added': [],
                          'author': {'email': 'phil.maia@gmail.com',
                                     'name': 'philippe',
                                     'username': 'maiaPhilippe'},
                          'committer': {'email': 'phil.maia@gmail.com',
                                        'name': 'philippe',
                                        'username': 'maiaPhilippe'},
                          'distinct': True,
                          'id': 'cbc97cbe5adb32d73a5696870e5a8c8515e3badd',
                          'message': '[BugFix] Fix commits collector',
                          'modified': ['app.py',
                                       'collections_edges/commit_collection.py',
                                       'collectors_and_savers/webhook_collector.py',
                                       'webhook/webhook_event_router.py',
                                       'webhook/webhook_repository_event.py',
                                       'webhook_graphql_queries/webhook_repo.graphql'],
                          'removed': [],
                          'timestamp': '2018-04-11T10:55:55-03:00',
                          'tree_id': 'bc6d83713838dd1110e864114eda59de879834d8',
                          'url': 'https://github.com/stone-payments/athena/commit/cbc97cbe5adb32d73a5696870e5a8c8515e3badd'}],
             'compare': 'https://github.com/stone-payments/athena/compare/2bbf15e032fa...cbc97cbe5adb',
             'created': False,
             'deleted': False,
             'forced': False,
             'head_commit': {'added': [],
                             'author': {'email': 'phil.maia@gmail.com',
                                        'name': 'philippe',
                                        'username': 'maiaPhilippe'},
                             'committer': {'email': 'phil.maia@gmail.com',
                                           'name': 'philippe',
                                           'username': 'maiaPhilippe'},
                             'distinct': True,
                             'id': 'cbc97cbe5adb32d73a5696870e5a8c8515e3badd',
                             'message': '[BugFix] Fix commits collector',
                             'modified': ['app.py',
                                          'collections_edges/commit_collection.py',
                                          'collectors_and_savers/webhook_collector.py',
                                          'webhook/webhook_event_router.py',
                                          'webhook/webhook_repository_event.py',
                                          'webhook_graphql_queries/webhook_repo.graphql'],
                             'removed': [],
                             'timestamp': '2018-04-11T10:55:55-03:00',
                             'tree_id': 'bc6d83713838dd1110e864114eda59de879834d8',
                             'url': 'https://github.com/stone-payments/athena/commit/cbc97cbe5adb32d73a5696870e5a8c8515e3badd'},
             'organization': {'avatar_url': 'https://avatars1.githubusercontent.com/u/8750624?v=4',
                              'description': 'Pensar fora da máquina só é possível quando '
                                             'se trabalha com tecnologia humana de ponta.',
                              'events_url': 'https://api.github.com/orgs/stone-payments/events',
                              'hooks_url': 'https://api.github.com/orgs/stone-payments/hooks',
                              'id': 8750624,
                              'issues_url': 'https://api.github.com/orgs/stone-payments/issues',
                              'login': 'stone-payments',
                              'members_url': 'https://api.github.com/orgs/stone-payments/members{/member}',
                              'public_members_url': 'https://api.github.com/orgs/stone-payments/public_members{/member}',
                              'repos_url': 'https://api.github.com/orgs/stone-payments/repos',
                              'url': 'https://api.github.com/orgs/stone-payments'},
             'pusher': {'email': 'philippe.maia@stone.com.br', 'name': 'maiaPhilippe'},
             'ref': 'refs/heads/dev_2.0',
             'repository': {'archive_url': 'https://api.github.com/repos/stone-payments/athena/{archive_format}{/ref}',
                            'archived': False,
                            'assignees_url': 'https://api.github.com/repos/stone-payments/athena/assignees{/user}',
                            'blobs_url': 'https://api.github.com/repos/stone-payments/athena/git/blobs{/sha}',
                            'branches_url': 'https://api.github.com/repos/stone-payments/athena/branches{/branch}',
                            'clone_url': 'https://github.com/stone-payments/athena.git',
                            'collaborators_url': 'https://api.github.com/repos/stone-payments/athena/collaborators{/collaborator}',
                            'comments_url': 'https://api.github.com/repos/stone-payments/athena/comments{/number}',
                            'commits_url': 'https://api.github.com/repos/stone-payments/athena/commits{/sha}',
                            'compare_url': 'https://api.github.com/repos/stone-payments/athena/compare/{base}...{head}',
                            'contents_url': 'https://api.github.com/repos/stone-payments/athena/contents/{+path}',
                            'contributors_url': 'https://api.github.com/repos/stone-payments/athena/contributors',
                            'created_at': 1503684822,
                            'default_branch': 'master',
                            'deployments_url': 'https://api.github.com/repos/stone-payments/athena/deployments',
                            'description': 'GitHub BI :green_heart: :eyes:',
                            'downloads_url': 'https://api.github.com/repos/stone-payments/athena/downloads',
                            'events_url': 'https://api.github.com/repos/stone-payments/athena/events',
                            'fork': False,
                            'forks': 0,
                            'forks_count': 0,
                            'forks_url': 'https://api.github.com/repos/stone-payments/athena/forks',
                            'full_name': 'stone-payments/athena',
                            'git_commits_url': 'https://api.github.com/repos/stone-payments/athena/git/commits{/sha}',
                            'git_refs_url': 'https://api.github.com/repos/stone-payments/athena/git/refs{/sha}',
                            'git_tags_url': 'https://api.github.com/repos/stone-payments/athena/git/tags{/sha}',
                            'git_url': 'git://github.com/stone-payments/athena.git',
                            'has_downloads': True,
                            'has_issues': True,
                            'has_pages': False,
                            'has_projects': True,
                            'has_wiki': True,
                            'homepage': '',
                            'hooks_url': 'https://api.github.com/repos/stone-payments/athena/hooks',
                            'html_url': 'https://github.com/stone-payments/athena',
                            'id': 101430313,
                            'issue_comment_url': 'https://api.github.com/repos/stone-payments/athena/issues/comments{/number}',
                            'issue_events_url': 'https://api.github.com/repos/stone-payments/athena/issues/events{/number}',
                            'issues_url': 'https://api.github.com/repos/stone-payments/athena/issues{/number}',
                            'keys_url': 'https://api.github.com/repos/stone-payments/athena/keys{/key_id}',
                            'labels_url': 'https://api.github.com/repos/stone-payments/athena/labels{/name}',
                            'language': 'Python',
                            'languages_url': 'https://api.github.com/repos/stone-payments/athena/languages',
                            'license': {'key': 'apache-2.0',
                                        'name': 'Apache License 2.0',
                                        'spdx_id': 'Apache-2.0',
                                        'url': 'https://api.github.com/licenses/apache-2.0'},
                            'master_branch': 'master',
                            'merges_url': 'https://api.github.com/repos/stone-payments/athena/merges',
                            'milestones_url': 'https://api.github.com/repos/stone-payments/athena/milestones{/number}',
                            'mirror_url': None,
                            'name': 'athena',
                            'notifications_url': 'https://api.github.com/repos/stone-payments/athena/notifications{?since,all,participating}',
                            'open_issues': 0,
                            'open_issues_count': 0,
                            'organization': 'stone-payments',
                            'owner': {'avatar_url': 'https://avatars1.githubusercontent.com/u/8750624?v=4',
                                      'email': 'opensource@stone.com.br',
                                      'events_url': 'https://api.github.com/users/stone-payments/events{/privacy}',
                                      'followers_url': 'https://api.github.com/users/stone-payments/followers',
                                      'following_url': 'https://api.github.com/users/stone-payments/following{/other_user}',
                                      'gists_url': 'https://api.github.com/users/stone-payments/gists{/gist_id}',
                                      'gravatar_id': '',
                                      'html_url': 'https://github.com/stone-payments',
                                      'id': 8750624,
                                      'login': 'stone-payments',
                                      'name': 'stone-payments',
                                      'organizations_url': 'https://api.github.com/users/stone-payments/orgs',
                                      'received_events_url': 'https://api.github.com/users/stone-payments/received_events',
                                      'repos_url': 'https://api.github.com/users/stone-payments/repos',
                                      'site_admin': False,
                                      'starred_url': 'https://api.github.com/users/stone-payments/starred{/owner}{/repo}',
                                      'subscriptions_url': 'https://api.github.com/users/stone-payments/subscriptions',
                                      'type': 'Organization',
                                      'url': 'https://api.github.com/users/stone-payments'},
                            'private': False,
                            'pulls_url': 'https://api.github.com/repos/stone-payments/athena/pulls{/number}',
                            'pushed_at': 1523454961,
                            'releases_url': 'https://api.github.com/repos/stone-payments/athena/releases{/id}',
                            'size': 887,
                            'ssh_url': 'git@github.com:stone-payments/athena.git',
                            'stargazers': 5,
                            'stargazers_count': 5,
                            'stargazers_url': 'https://api.github.com/repos/stone-payments/athena/stargazers',
                            'statuses_url': 'https://api.github.com/repos/stone-payments/athena/statuses/{sha}',
                            'subscribers_url': 'https://api.github.com/repos/stone-payments/athena/subscribers',
                            'subscription_url': 'https://api.github.com/repos/stone-payments/athena/subscription',
                            'svn_url': 'https://github.com/stone-payments/athena',
                            'tags_url': 'https://api.github.com/repos/stone-payments/athena/tags',
                            'teams_url': 'https://api.github.com/repos/stone-payments/athena/teams',
                            'trees_url': 'https://api.github.com/repos/stone-payments/athena/git/trees{/sha}',
                            'updated_at': '2018-04-10T00:23:14Z',
                            'url': 'https://github.com/stone-payments/athena',
                            'watchers': 5,
                            'watchers_count': 5},
             'sender': {'avatar_url': 'https://avatars2.githubusercontent.com/u/17355677?v=4',
                        'events_url': 'https://api.github.com/users/maiaPhilippe/events{/privacy}',
                        'followers_url': 'https://api.github.com/users/maiaPhilippe/followers',
                        'following_url': 'https://api.github.com/users/maiaPhilippe/following{/other_user}',
                        'gists_url': 'https://api.github.com/users/maiaPhilippe/gists{/gist_id}',
                        'gravatar_id': '',
                        'html_url': 'https://github.com/maiaPhilippe',
                        'id': 17355677,
                        'login': 'maiaPhilippe',
                        'organizations_url': 'https://api.github.com/users/maiaPhilippe/orgs',
                        'received_events_url': 'https://api.github.com/users/maiaPhilippe/received_events',
                        'repos_url': 'https://api.github.com/users/maiaPhilippe/repos',
                        'site_admin': False,
                        'starred_url': 'https://api.github.com/users/maiaPhilippe/starred{/owner}{/repo}',
                        'subscriptions_url': 'https://api.github.com/users/maiaPhilippe/subscriptions',
                        'type': 'User',
                        'url': 'https://api.github.com/users/maiaPhilippe'}}
            ]


def dev_events():
    return [
    "organization",
    {
        "action": "member_added",
        "invitation": {
            "id": 3294302,
            "login": "gomex",
            "email": None,
            "role": "direct_member"
        },
        "membership": {
            "url": "https://api.github.com/orgs/baxterandthehackers/memberships/baxterthehacker",
            "state": "active",
            "role": "member",
            "organization_url": "https://api.github.com/orgs/baxterandthehackers",
            "user": {
                "login": "gomex",
                "id": 7649605,
                "avatar_url": "https://avatars.githubusercontent.com/u/17085448?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/baxterthehacker",
                "html_url": "https://github.com/baxterthehacker",
                "followers_url": "https://api.github.com/users/baxterthehacker/followers",
                "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
                "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
                "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
                "repos_url": "https://api.github.com/users/baxterthehacker/repos",
                "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
                "type": "User",
                "site_admin": False
            }
        },
        "organization": {
            "login": "baxterandthehackers",
            "id": 4312013,
            "url": "https://api.github.com/orgs/baxterandthehackers",
            "repos_url": "https://api.github.com/orgs/baxterandthehackers/repos",
            "events_url": "https://api.github.com/orgs/baxterandthehackers/events",
            "hooks_url": "https://api.github.com/orgs/baxterandthehackers/hooks",
            "issues_url": "https://api.github.com/orgs/baxterandthehackers/issues",
            "members_url": "https://api.github.com/orgs/baxterandthehackers/members{/member}",
            "public_members_url": "https://api.github.com/orgs/baxterandthehackers/public_members{/member}",
            "avatar_url": "https://avatars.githubusercontent.com/u/4312013?v=3",
            "description": ""
        },
        "sender": {
            "login": "baxterthehacker",
            "id": 7649605,
            "avatar_url": "https://avatars.githubusercontent.com/u/7649605?v=3",
            "gravatar_id": "",
            "url": "https://api.github.com/users/baxterthehacker",
            "html_url": "https://github.com/baxterthehacker",
            "followers_url": "https://api.github.com/users/baxterthehacker/followers",
            "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
            "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
            "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
            "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
            "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
            "repos_url": "https://api.github.com/users/baxterthehacker/repos",
            "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
            "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
            "type": "User",
            "site_admin": True
        }
    }
]


def teams_events():
    return [
        "team",
        {
            "action": "created",
            "team": {
                "name": "all-devs",
                "id": 2175394,
                "slug": "all-devs",
                "description": "",
                "privacy": "secret",
                "url": "https:/api.github.com/teams/2175394",
                "members_url": "https:/api.github.com/teams/2175394/members{/member}",
                "repositories_url": "https:/api.github.com/teams/2175394/repos",
                "permission": "pull"
            },
            "organization": {
                "login": "stone-payments",
                "id": 4312013,
                "url": "https://api.github.com/orgs/baxterandthehackers",
                "repos_url": "https://api.github.com/orgs/baxterandthehackers/repos",
                "events_url": "https://api.github.com/orgs/baxterandthehackers/events",
                "hooks_url": "https://api.github.com/orgs/baxterandthehackers/hooks",
                "issues_url": "https://api.github.com/orgs/baxterandthehackers/issues",
                "members_url": "https://api.github.com/orgs/baxterandthehackers/members{/member}",
                "public_members_url": "https://api.github.com/orgs/baxterandthehackers/public_members{/member}",
                "avatar_url": "https://avatars.githubusercontent.com/u/4312013?v=3",
                "description": ""
            },
            "sender": {
                "login": "baxterthehacker",
                "id": 6752317,
                "avatar_url": "https://avatars.githubusercontent.com/u/6752317?v=3",
                "gravatar_id": "",
                "url": "https://api.github.com/users/baxterthehacker",
                "html_url": "https://github.com/baxterthehacker",
                "followers_url": "https://api.github.com/users/baxterthehacker/followers",
                "following_url": "https://api.github.com/users/baxterthehacker/following{/other_user}",
                "gists_url": "https://api.github.com/users/baxterthehacker/gists{/gist_id}",
                "starred_url": "https://api.github.com/users/baxterthehacker/starred{/owner}{/repo}",
                "subscriptions_url": "https://api.github.com/users/baxterthehacker/subscriptions",
                "organizations_url": "https://api.github.com/users/baxterthehacker/orgs",
                "repos_url": "https://api.github.com/users/baxterthehacker/repos",
                "events_url": "https://api.github.com/users/baxterthehacker/events{/privacy}",
                "received_events_url": "https://api.github.com/users/baxterthehacker/received_events",
                "type": "User",
                "site_admin": False
            }
        }
    ]


def team_edit():
    return [
        "team",
        {'action': 'edited',
         'changes': {'repository': {'permissions': {'from': {'admin': False,
                                                             'pull': True,
                                                             'push': False}}}},
         'organization': {'avatar_url': 'https://avatars1.githubusercontent.com/u/8750624?v=4',
                          'description': 'Pensar fora da máquina só é possível quando '
                                         'se trabalha com tecnologia humana de ponta.',
                          'events_url': 'https://api.github.com/orgs/stone-payments/events',
                          'hooks_url': 'https://api.github.com/orgs/stone-payments/hooks',
                          'id': 8750624,
                          'issues_url': 'https://api.github.com/orgs/stone-payments/issues',
                          'login': 'stone-payments',
                          'members_url': 'https://api.github.com/orgs/stone-payments/members{/member}',
                          'public_members_url': 'https://api.github.com/orgs/stone-payments/public_members{/member}',
                          'repos_url': 'https://api.github.com/orgs/stone-payments/repos',
                          'url': 'https://api.github.com/orgs/stone-payments'},
         'repository': {
             'archive_url': 'https://api.github.com/repos/stone-payments/github-webhook/{archive_format}{/ref}',
             'archived': False,
             'assignees_url': 'https://api.github.com/repos/stone-payments/github-webhook/assignees{/user}',
             'blobs_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/blobs{/sha}',
             'branches_url': 'https://api.github.com/repos/stone-payments/github-webhook/branches{/branch}',
             'clone_url': 'https://github.com/stone-payments/github-webhook.git',
             'collaborators_url': 'https://api.github.com/repos/stone-payments/github-webhook/collaborators{/collaborator}',
             'comments_url': 'https://api.github.com/repos/stone-payments/github-webhook/comments{/number}',
             'commits_url': 'https://api.github.com/repos/stone-payments/github-webhook/commits{/sha}',
             'compare_url': 'https://api.github.com/repos/stone-payments/github-webhook/compare/{base}...{head}',
             'contents_url': 'https://api.github.com/repos/stone-payments/github-webhook/contents/{+path}',
             'contributors_url': 'https://api.github.com/repos/stone-payments/github-webhook/contributors',
             'created_at': '2018-03-14T13:28:01Z',
             'default_branch': 'master',
             'deployments_url': 'https://api.github.com/repos/stone-payments/github-webhook/deployments',
             'description': None,
             'downloads_url': 'https://api.github.com/repos/stone-payments/github-webhook/downloads',
             'events_url': 'https://api.github.com/repos/stone-payments/github-webhook/events',
             'fork': False,
             'forks': 0,
             'forks_count': 0,
             'forks_url': 'https://api.github.com/repos/stone-payments/github-webhook/forks',
             'full_name': 'stone-payments/github-webhook',
             'git_commits_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/commits{/sha}',
             'git_refs_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/refs{/sha}',
             'git_tags_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/tags{/sha}',
             'git_url': 'git://github.com/stone-payments/github-webhook.git',
             'has_downloads': True,
             'has_issues': True,
             'has_pages': False,
             'has_projects': True,
             'has_wiki': True,
             'homepage': None,
             'hooks_url': 'https://api.github.com/repos/stone-payments/github-webhook/hooks',
             'html_url': 'https://github.com/stone-payments/github-webhook',
             'id': 125216660,
             'issue_comment_url': 'https://api.github.com/repos/stone-payments/github-webhook/issues/comments{/number}',
             'issue_events_url': 'https://api.github.com/repos/stone-payments/github-webhook/issues/events{/number}',
             'issues_url': 'https://api.github.com/repos/stone-payments/github-webhook/issues{/number}',
             'keys_url': 'https://api.github.com/repos/stone-payments/github-webhook/keys{/key_id}',
             'labels_url': 'https://api.github.com/repos/stone-payments/github-webhook/labels{/name}',
             'language': 'Python',
             'languages_url': 'https://api.github.com/repos/stone-payments/github-webhook/languages',
             'license': {'key': 'mit',
                         'name': 'MIT License',
                         'spdx_id': 'MIT',
                         'url': 'https://api.github.com/licenses/mit'},
             'merges_url': 'https://api.github.com/repos/stone-payments/github-webhook/merges',
             'milestones_url': 'https://api.github.com/repos/stone-payments/github-webhook/milestones{/number}',
             'mirror_url': None,
             'name': 'github-webhook',
             'notifications_url': 'https://api.github.com/repos/stone-payments/github-webhook/notifications{?since,all,participating}',
             'open_issues': 1,
             'open_issues_count': 1,
             'owner': {'avatar_url': 'https://avatars1.githubusercontent.com/u/8750624?v=4',
                       'events_url': 'https://api.github.com/users/stone-payments/events{/privacy}',
                       'followers_url': 'https://api.github.com/users/stone-payments/followers',
                       'following_url': 'https://api.github.com/users/stone-payments/following{/other_user}',
                       'gists_url': 'https://api.github.com/users/stone-payments/gists{/gist_id}',
                       'gravatar_id': '',
                       'html_url': 'https://github.com/stone-payments',
                       'id': 8750624,
                       'login': 'stone-payments',
                       'organizations_url': 'https://api.github.com/users/stone-payments/orgs',
                       'received_events_url': 'https://api.github.com/users/stone-payments/received_events',
                       'repos_url': 'https://api.github.com/users/stone-payments/repos',
                       'site_admin': False,
                       'starred_url': 'https://api.github.com/users/stone-payments/starred{/owner}{/repo}',
                       'subscriptions_url': 'https://api.github.com/users/stone-payments/subscriptions',
                       'type': 'Organization',
                       'url': 'https://api.github.com/users/stone-payments'},
             'permissions': {'admin': False, 'pull': True, 'push': True},
             'private': True,
             'pulls_url': 'https://api.github.com/repos/stone-payments/github-webhook/pulls{/number}',
             'pushed_at': '2018-04-09T18:44:52Z',
             'releases_url': 'https://api.github.com/repos/stone-payments/github-webhook/releases{/id}',
             'size': 47,
             'ssh_url': 'git@github.com:stone-payments/github-webhook.git',
             'stargazers_count': 0,
             'stargazers_url': 'https://api.github.com/repos/stone-payments/github-webhook/stargazers',
             'statuses_url': 'https://api.github.com/repos/stone-payments/github-webhook/statuses/{sha}',
             'subscribers_url': 'https://api.github.com/repos/stone-payments/github-webhook/subscribers',
             'subscription_url': 'https://api.github.com/repos/stone-payments/github-webhook/subscription',
             'svn_url': 'https://github.com/stone-payments/github-webhook',
             'tags_url': 'https://api.github.com/repos/stone-payments/github-webhook/tags',
             'teams_url': 'https://api.github.com/repos/stone-payments/github-webhook/teams',
             'trees_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/trees{/sha}',
             'updated_at': '2018-04-09T18:02:01Z',
             'url': 'https://api.github.com/repos/stone-payments/github-webhook',
             'watchers': 0,
             'watchers_count': 0},
         'sender': {'avatar_url': 'https://avatars2.githubusercontent.com/u/17355677?v=4',
                    'events_url': 'https://api.github.com/users/maiaPhilippe/events{/privacy}',
                    'followers_url': 'https://api.github.com/users/maiaPhilippe/followers',
                    'following_url': 'https://api.github.com/users/maiaPhilippe/following{/other_user}',
                    'gists_url': 'https://api.github.com/users/maiaPhilippe/gists{/gist_id}',
                    'gravatar_id': '',
                    'html_url': 'https://github.com/maiaPhilippe',
                    'id': 17355677,
                    'login': 'maiaPhilippe',
                    'organizations_url': 'https://api.github.com/users/maiaPhilippe/orgs',
                    'received_events_url': 'https://api.github.com/users/maiaPhilippe/received_events',
                    'repos_url': 'https://api.github.com/users/maiaPhilippe/repos',
                    'site_admin': False,
                    'starred_url': 'https://api.github.com/users/maiaPhilippe/starred{/owner}{/repo}',
                    'subscriptions_url': 'https://api.github.com/users/maiaPhilippe/subscriptions',
                    'type': 'User',
                    'url': 'https://api.github.com/users/maiaPhilippe'},
         'team': {'description': '',
                  'id': 2684645,
                  'members_url': 'https://api.github.com/teams/2684645/members{/member}',
                  'name': 'Gestao-TI',
                  'permission': 'pull',
                  'privacy': 'closed',
                  'repositories_url': 'https://api.github.com/teams/2684645/repos',
                  'slug': 'gestao-ti',
                  'url': 'https://api.github.com/teams/2684645'}}
    ]


def team_add_repository():
    return [
    "team",
{'action': 'added_to_repository',
 'organization': {'avatar_url': 'https://avatars1.githubusercontent.com/u/8750624?v=4',
                  'description': 'Pensar fora da máquina só é possível quando '
                                 'se trabalha com tecnologia humana de ponta.',
                  'events_url': 'https://api.github.com/orgs/stone-payments/events',
                  'hooks_url': 'https://api.github.com/orgs/stone-payments/hooks',
                  'id': 8750624,
                  'issues_url': 'https://api.github.com/orgs/stone-payments/issues',
                  'login': 'stone-payments',
                  'members_url': 'https://api.github.com/orgs/stone-payments/members{/member}',
                  'public_members_url': 'https://api.github.com/orgs/stone-payments/public_members{/member}',
                  'repos_url': 'https://api.github.com/orgs/stone-payments/repos',
                  'url': 'https://api.github.com/orgs/stone-payments'},
'repository': {'archive_url': 'https://api.github.com/repos/stone-payments/github-webhook/{archive_format}{/ref}',
                'archived': False,
                'assignees_url': 'https://api.github.com/repos/stone-payments/github-webhook/assignees{/user}',
                'blobs_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/blobs{/sha}',
                'branches_url': 'https://api.github.com/repos/stone-payments/github-webhook/branches{/branch}',
                'clone_url': 'https://github.com/stone-payments/github-webhook.git',
                'collaborators_url': 'https://api.github.com/repos/stone-payments/github-webhook/collaborators{/collaborator}',
                'comments_url': 'https://api.github.com/repos/stone-payments/github-webhook/comments{/number}',
                'commits_url': 'https://api.github.com/repos/stone-payments/github-webhook/commits{/sha}',
                'compare_url': 'https://api.github.com/repos/stone-payments/github-webhook/compare/{base}...{head}',
                'contents_url': 'https://api.github.com/repos/stone-payments/github-webhook/contents/{+path}',
                'contributors_url': 'https://api.github.com/repos/stone-payments/github-webhook/contributors',
                'created_at': '2018-03-14T13:28:01Z',
                'default_branch': 'master',
                'deployments_url': 'https://api.github.com/repos/stone-payments/github-webhook/deployments',
                'description': None,
                'downloads_url': 'https://api.github.com/repos/stone-payments/github-webhook/downloads',
                'events_url': 'https://api.github.com/repos/stone-payments/github-webhook/events',
                'fork': False,
                'forks': 0,
                'forks_count': 0,
                'forks_url': 'https://api.github.com/repos/stone-payments/github-webhook/forks',
                'full_name': 'stone-payments/github-webhook',
                'git_commits_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/commits{/sha}',
                'git_refs_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/refs{/sha}',
                'git_tags_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/tags{/sha}',
                'git_url': 'git://github.com/stone-payments/github-webhook.git',
                'has_downloads': True,
                'has_issues': True,
                'has_pages': False,
                'has_projects': True,
                'has_wiki': True,
                'homepage': None,
                'hooks_url': 'https://api.github.com/repos/stone-payments/github-webhook/hooks',
                'html_url': 'https://github.com/stone-payments/github-webhook',
                'id': 125216660,
                'issue_comment_url': 'https://api.github.com/repos/stone-payments/github-webhook/issues/comments{/number}',
                'issue_events_url': 'https://api.github.com/repos/stone-payments/github-webhook/issues/events{/number}',
                'issues_url': 'https://api.github.com/repos/stone-payments/github-webhook/issues{/number}',
                'keys_url': 'https://api.github.com/repos/stone-payments/github-webhook/keys{/key_id}',
                'labels_url': 'https://api.github.com/repos/stone-payments/github-webhook/labels{/name}',
                'language': 'Python',
                'languages_url': 'https://api.github.com/repos/stone-payments/github-webhook/languages',
                'license': {'key': 'mit',
                            'name': 'MIT License',
                            'spdx_id': 'MIT',
                            'url': 'https://api.github.com/licenses/mit'},
                'merges_url': 'https://api.github.com/repos/stone-payments/github-webhook/merges',
                'milestones_url': 'https://api.github.com/repos/stone-payments/github-webhook/milestones{/number}',
                'mirror_url': None,
                'name': 'github-webhook',
                'notifications_url': 'https://api.github.com/repos/stone-payments/github-webhook/notifications{?since,all,participating}',
                'open_issues': 1,
                'open_issues_count': 1,
                'owner': {'avatar_url': 'https://avatars1.githubusercontent.com/u/8750624?v=4',
                          'events_url': 'https://api.github.com/users/stone-payments/events{/privacy}',
                          'followers_url': 'https://api.github.com/users/stone-payments/followers',
                          'following_url': 'https://api.github.com/users/stone-payments/following{/other_user}',
                          'gists_url': 'https://api.github.com/users/stone-payments/gists{/gist_id}',
                          'gravatar_id': '',
                          'html_url': 'https://github.com/stone-payments',
                          'id': 8750624,
                          'login': 'stone-payments',
                          'organizations_url': 'https://api.github.com/users/stone-payments/orgs',
                          'received_events_url': 'https://api.github.com/users/stone-payments/received_events',
                          'repos_url': 'https://api.github.com/users/stone-payments/repos',
                          'site_admin': False,
                          'starred_url': 'https://api.github.com/users/stone-payments/starred{/owner}{/repo}',
                          'subscriptions_url': 'https://api.github.com/users/stone-payments/subscriptions',
                          'type': 'Organization',
                          'url': 'https://api.github.com/users/stone-payments'},
                'permissions': {'admin': False, 'pull': True, 'push': False},
                'private': True,
                'pulls_url': 'https://api.github.com/repos/stone-payments/github-webhook/pulls{/number}',
                'pushed_at': '2018-04-09T18:44:52Z',
                'releases_url': 'https://api.github.com/repos/stone-payments/github-webhook/releases{/id}',
                'size': 47,
                'ssh_url': 'git@github.com:stone-payments/github-webhook.git',
                'stargazers_count': 0,
                'stargazers_url': 'https://api.github.com/repos/stone-payments/github-webhook/stargazers',
                'statuses_url': 'https://api.github.com/repos/stone-payments/github-webhook/statuses/{sha}',
                'subscribers_url': 'https://api.github.com/repos/stone-payments/github-webhook/subscribers',
                'subscription_url': 'https://api.github.com/repos/stone-payments/github-webhook/subscription',
                'svn_url': 'https://github.com/stone-payments/github-webhook',
                'tags_url': 'https://api.github.com/repos/stone-payments/github-webhook/tags',
                'teams_url': 'https://api.github.com/repos/stone-payments/github-webhook/teams',
                'trees_url': 'https://api.github.com/repos/stone-payments/github-webhook/git/trees{/sha}',
                'updated_at': '2018-04-09T18:02:01Z',
                'url': 'https://api.github.com/repos/stone-payments/github-webhook',
                'watchers': 0,
                'watchers_count': 0},
 'sender': {'avatar_url': 'https://avatars2.githubusercontent.com/u/17355677?v=4',
            'events_url': 'https://api.github.com/users/maiaPhilippe/events{/privacy}',
            'followers_url': 'https://api.github.com/users/maiaPhilippe/followers',
            'following_url': 'https://api.github.com/users/maiaPhilippe/following{/other_user}',
            'gists_url': 'https://api.github.com/users/maiaPhilippe/gists{/gist_id}',
            'gravatar_id': '',
            'html_url': 'https://github.com/maiaPhilippe',
            'id': 17355677,
            'login': 'maiaPhilippe',
            'organizations_url': 'https://api.github.com/users/maiaPhilippe/orgs',
            'received_events_url': 'https://api.github.com/users/maiaPhilippe/received_events',
            'repos_url': 'https://api.github.com/users/maiaPhilippe/repos',
            'site_admin': False,
            'starred_url': 'https://api.github.com/users/maiaPhilippe/starred{/owner}{/repo}',
            'subscriptions_url': 'https://api.github.com/users/maiaPhilippe/subscriptions',
            'type': 'User',
            'url': 'https://api.github.com/users/maiaPhilippe'},
 'team': {'description': '',
          'id': 2728277,
          'members_url': 'https://api.github.com/teams/2728277/members{/member}',
          'name': 'team_test',
          'permission': 'pull',
          'privacy': 'secret',
          'repositories_url': 'https://api.github.com/teams/2728277/repos',
          'slug': 'team_test',
          'url': 'https://api.github.com/teams/2728277'}}
]